version: 2
jobs:
  build:
    docker:
      - image: regentmarkets/debian-pg:wheezy-5.26.2-96
    steps:
      - checkout
      - run:
          name: Run smoke test
          command: dzil smoke --release --author
      - run:
          name: Run coverage test
          command: dzil cover -test -report codecov
      - run:
          name: Run extended author test
          command: dzil xtest