version: 2.1
jobs:
  test:
    docker:
      - image: regentmarkets/debian-pg:stretch-5.26.2-96
    steps:
      - checkout
      - &prepare
        run:
          name: prepare
          command: |
            apt-get update && apt-get install -y --no-install-recommends libssl-dev zlib1g-dev pkg-config
            cpanm --quiet --notest Dist::Zilla Dist::Zilla::App::Command::cover Devel::Cover::Report::Codecov
            cpanm --quiet --notest $(dzil authordeps --missing)
            cpanm -n --installdeps .
            cpanm --quiet --notest $(dzil listdeps --author --missing)
      - &start_redis
        run:
          name: Start Redis
          command: redis-server --port 6379 --daemonize yes
      - &setup_env
        run:
          name: Setup Environment Variables
          command: |
            echo 'export TEST_REDIS=redis://localhost:6379' >> $BASH_ENV
      - run:
          name: Run smoke test
          command: dzil smoke --release --author
      - run:
          name: Run coverage test
          command: dzil cover -test -report codecov
      - run:
          name: Run extended author test
          command: dzil xtest
  release:
    docker:
      - image: regentmarkets/debian-pg:stretch-5.26.2-96
    steps:
      - checkout
      - *prepare
      - *start_redis
      - *setup_env
      - run:
          name: setup PAUSE account
          command: |
            echo -e "user $PAUSE_USER\npassword $PAUSE_PASSWORD\n" >> ~/.pause
      - run:
          name: setup git
          command: |
            git config --global user.email "circleci@binary.com"
            git config --global user.name "circleci"
            # set remote github because dzil will push to github
            # https://metacpan.org/release/DERIV/Dist-Zilla-PluginBundle-Author-DERIV-0.003/source/lib/Dist/Zilla/PluginBundle/Author/DERIV.pm#L122
            git remote add github $(git remote get-url origin)
      - run:
          name: Release to PAUSE
          command: |
            if grep -Pzq '\{\{\$NEXT\}\}\n\s*\n' Changes
            then
                echo "No changes, no need release"
                exit 0
            fi
            cat ~/.pause

workflows:
  build-workflow:
    jobs:
    - test
    - release:
       context: release-binary
       requires:
         - test

