name: Build workflow
run-name: Build workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    services:
      redis:
        image: redis
      postgres:
        image: postgres
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Prepare Environment
        run: |
          apt-get update && apt-get install -y --no-install-recommends libssl-dev cpanminus make gcc openssl zlib1g-dev pkg-config git
          cpanm --quiet --notest Dist::Zilla Dist::Zilla::App::Command::cover Devel::Cover::Report::Codecov
          cpanm --quiet --notest $(dzil authordeps --missing)
          cpanm -n --installdeps .
          cpanm --quiet --notest $(dzil listdeps --author --missing)
